class Match {
    file = "\z\foof\addons\main\functions\match";

    class matchAddWebEventHandler {};
    class matchAnnounceSnapshotPhase {};
    class matchApplyDurationSetting {};
    class matchApplyPersistence {};
    class matchAccrueSectorPresence {};
    class matchBuildPersistence {};
    class matchBuildOperationSector {};
    class matchBuildSnapshot {};
    class matchClientInit {};
    class matchDeploymentBlockedArea {};
    class matchFinalizeCampaignDay {};
    class matchHandleUiEvent {};
    class matchInitServer {};
    class matchNotifyPhase {};
    class matchOpenDialog {};
    class matchOperationSectorObjectiveIds {};
    class matchPhaseLabel {};
    class matchPostInit { postInit = 1; };
    class matchPreInit { preInit = 1; };
    class matchReceiveSnapshot {};
    class matchRequestSnapshot {};
    class matchRebuildOperationSector {};
    class matchScoreCampaignDay {};
    class matchSelectOperationObjective {};
    class matchSendSnapshot {};
    class matchSideOwnedCellCount {};
    class matchStartLoop {};
    class matchStartOperation {};
    class matchStartPhase {};
    class matchTick {};
    class matchToggleDialog {};
    class matchUpdateFrontlineSelection {};
    class matchUpdateDialog {};
    class matchUpdateSectorMarker {};
    class matchWebAction {};
};
