if (!isServer) exitWith { [] };

private _dayResults = [];

{
    _dayResults pushBack [
        ["day", _x get "day"],
        ["operationId", _x get "operationId"],
        ["objectiveId", _x get "objectiveId"],
        ["objectiveName", _x get "objectiveName"],
        ["objectiveOwner", _x get "objectiveOwner"],
        ["initialOwner", _x get "initialOwner"],
        ["sectorObjectiveIds", _x get "sectorObjectiveIds"],
        ["secondaryObjectiveIds", _x get "secondaryObjectiveIds"],
        ["secondaryObjectiveCount", _x get "secondaryObjectiveCount"],
        ["winner", _x get "winner"],
        ["nextOffensiveSide", _x get "nextOffensiveSide"],
        ["westScore", _x get "westScore"],
        ["eastScore", _x get "eastScore"],
        ["westPrimaryObjectiveScore", _x get "westPrimaryObjectiveScore"],
        ["eastPrimaryObjectiveScore", _x get "eastPrimaryObjectiveScore"],
        ["westPrimaryCaptureScore", _x get "westPrimaryCaptureScore"],
        ["eastPrimaryCaptureScore", _x get "eastPrimaryCaptureScore"],
        ["westSecondaryHeld", _x get "westSecondaryHeld"],
        ["eastSecondaryHeld", _x get "eastSecondaryHeld"],
        ["westSecondaryObjectiveScore", _x get "westSecondaryObjectiveScore"],
        ["eastSecondaryObjectiveScore", _x get "eastSecondaryObjectiveScore"],
        ["westSecondaryCaptureScore", _x get "westSecondaryCaptureScore"],
        ["eastSecondaryCaptureScore", _x get "eastSecondaryCaptureScore"],
        ["westCellDelta", _x get "westCellDelta"],
        ["eastCellDelta", _x get "eastCellDelta"],
        ["westCellGainScore", _x get "westCellGainScore"],
        ["eastCellGainScore", _x get "eastCellGainScore"],
        ["westTicketsDrained", _x get "westTicketsDrained"],
        ["eastTicketsDrained", _x get "eastTicketsDrained"],
        ["westTicketDrainScore", _x get "westTicketDrainScore"],
        ["eastTicketDrainScore", _x get "eastTicketDrainScore"],
        ["westSectorPresenceScore", _x get "westSectorPresenceScore"],
        ["eastSectorPresenceScore", _x get "eastSectorPresenceScore"],
        ["westSectorPresenceTicks", _x get "westSectorPresenceTicks"],
        ["eastSectorPresenceTicks", _x get "eastSectorPresenceTicks"],
        ["endedAt", _x get "endedAt"]
    ];
} forEach FLO_MatchDayResults;

[
    ["revision", FLO_MatchState get "revision"],
    ["campaignDay", FLO_MatchState get "campaignDay"],
    ["phase", FLO_MatchState get "phase"],
    ["phaseNumber", FLO_MatchState get "phaseNumber"],
    ["phaseRemaining", round (((FLO_MatchState get "phaseEndsAt") - diag_tickTime) max 0)],
    ["operationId", FLO_MatchState get "operationId"],
    ["operationObjectiveId", FLO_MatchState get "operationObjectiveId"],
    ["operationObjectiveName", FLO_MatchState get "operationObjectiveName"],
    ["operationObjectivePosition", FLO_MatchState get "operationObjectivePosition"],
    ["operationObjectiveRadius", FLO_MatchState get "operationObjectiveRadius"],
    ["operationSectorPosition", FLO_MatchState get "operationSectorPosition"],
    ["operationSectorRadius", FLO_MatchState get "operationSectorRadius"],
    ["operationSectorObjectiveIds", FLO_MatchState get "operationSectorObjectiveIds"],
    ["operationSecondaryObjectiveIds", FLO_MatchState get "operationSecondaryObjectiveIds"],
    ["operationInitialSecondaryOwners", FLO_MatchState get "operationInitialSecondaryOwners"],
    ["operationInitialOwner", FLO_MatchState get "operationInitialOwner"],
    ["operationOffensiveSide", FLO_MatchState get "operationOffensiveSide"],
    ["operationAttackSide", FLO_MatchState get "operationAttackSide"],
    ["operationDefendSide", FLO_MatchState get "operationDefendSide"],
    ["operationInitialWestCells", FLO_MatchState get "operationInitialWestCells"],
    ["operationInitialEastCells", FLO_MatchState get "operationInitialEastCells"],
    ["operationInitialWestTickets", FLO_MatchState get "operationInitialWestTickets"],
    ["operationInitialEastTickets", FLO_MatchState get "operationInitialEastTickets"],
    ["operationWestSectorPresenceScore", FLO_MatchState get "operationWestSectorPresenceScore"],
    ["operationEastSectorPresenceScore", FLO_MatchState get "operationEastSectorPresenceScore"],
    ["operationWestSectorPresenceTicks", FLO_MatchState get "operationWestSectorPresenceTicks"],
    ["operationEastSectorPresenceTicks", FLO_MatchState get "operationEastSectorPresenceTicks"],
    ["plannedObjectiveId", FLO_MatchState get "plannedObjectiveId"],
    ["plannedObjectiveName", FLO_MatchState get "plannedObjectiveName"],
    ["plannedObjectivePosition", FLO_MatchState get "plannedObjectivePosition"],
    ["plannedObjectiveRadius", FLO_MatchState get "plannedObjectiveRadius"],
    ["plannedSectorPosition", FLO_MatchState get "plannedSectorPosition"],
    ["plannedSectorRadius", FLO_MatchState get "plannedSectorRadius"],
    ["plannedSectorObjectiveIds", FLO_MatchState get "plannedSectorObjectiveIds"],
    ["plannedSecondaryObjectiveIds", FLO_MatchState get "plannedSecondaryObjectiveIds"],
    ["plannedOffensiveSide", FLO_MatchState get "plannedOffensiveSide"],
    ["plannedAttackSide", FLO_MatchState get "plannedAttackSide"],
    ["plannedDefendSide", FLO_MatchState get "plannedDefendSide"],
    ["nextOffensiveSide", FLO_MatchState get "nextOffensiveSide"],
    ["campaignScoreWest", FLO_MatchState get "campaignScoreWest"],
    ["campaignScoreEast", FLO_MatchState get "campaignScoreEast"],
    ["dayResults", _dayResults]
]
