class Store {
    file = "\z\foof\addons\main\functions\store";

    class storeAddWebEventHandler {};
    class storeAddInventoryItem {};
    class storeApplyKit {};
    class storeAppendCatalogItem {};
    class storeBuildCatalog {};
    class storeBuildCatalogItem {};
    class storeBuildHydratePayload {};
    class storeBuildCategoryPayload {};
    class storeCategoryForVehicle {};
    class storeCategoryForWeapon {};
    class storeCheckout {};
    class storeFindVehicleSpawn {};
    class storeHandleUiEvent {};
    class storeInitServer {};
    class storeOpenDialog {};
    class storeFinalizeVehiclePlacement {};
    class storePendingVehiclesForAccess {};
    class storePostInit { postInit = 1; };
    class storePreInit { preInit = 1; };
    class storePriceClass {};
    class storeReceiveResponse {};
    class storeReceivePlacementResult {};
    class storeRequestCategory {};
    class storeRequestCheckout {};
    class storeRequestHydrate {};
    class storeSavedKitsDelete {};
    class storeSavedKitsLoad {};
    class storeSavedKitsSave {};
    class storeSelectedFaction {};
    class storeSendResponse {};
    class storeSpawnVehicle {};
    class storeStartVehiclePlacement {};
    class storeUpdateDialog {};
    class storeValidateAccess {};
    class storeWebAction {};
};
